name:                micro-lisp
version:             0.1.0.0
github:              "takoeight0821/micro-lisp"
license:             MIT
author:              "Yuya Kono"
maintainer:          "takohati0821@gmail.com"
copyright:           "2020 Yuya Kono"

extra-source-files:
- README.md
- ChangeLog.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/takoeight0821/micro-lisp#readme>

dependencies:
- base >= 4.7 && < 5
- containers
- lens
- megaparsec
- mtl
- transformers

ghc-options:
  - -Wall
  - -Wcompat
  - -Wincomplete-record-updates
  - -Wincomplete-uni-patterns
  - -Wmissing-deriving-strategies
  - -Wno-name-shadowing
  - -j4
  - +RTS -A128m -n2m -qg -RTS
  - -fwrite-ide-info
  - -hiedir=.hie
  
library:
  source-dirs: src

executables:
  micro-lisp-exe:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - micro-lisp

tests:
  micro-lisp-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - micro-lisp
